import { JSX } from "react";
import {
  C,
  CPP,
  CSS,
  CSHARP,
  JAVASCRIPT,
  TYPESCRIPT,
  DOCKERFILE,
  GO,
  GRAPHQL,
  HTML,
  JAVA,
  JSON,
  KOTLIN,
  LUA,
  MARKDOWN,
  MYSQL,
  DEFAULT,
} from "../components/icons";

export enum Language {
  APEX = "apex",
  AZCLI = "azcli",
  BAT = "bat",
  C = "c",
  CLOJURE = "clojure",
  COFFEESCRIPT = "coffeescript",
  CPP = "cpp",
  CSHARP = "csharp",
  CSP = "csp",
  CSS = "css",
  DOCKERFILE = "dockerfile",
  FSHARP = "fsharp",
  GO = "go",
  GRAPHQL = "graphql",
  HANDLEBARS = "handlebars",
  HTML = "html",
  INI = "ini",
  JAVA = "java",
  JAVASCRIPT = "javascript",
  JSON = "json",
  KOTLIN = "kotlin",
  LESS = "less",
  LUA = "lua",
  MARKDOWN = "markdown",
  MSDAX = "msdax",
  MYSQL = "mysql",
  OBJECTIVE_C = "objective-c",
  PASCAL = "pascal",
  PERL = "perl",
  PGSQL = "pgsql",
  PHP = "php",
  PLAINTEXT = "plaintext",
  POSTIATS = "postiats",
  POWERQUERY = "powerquery",
  POWERSHELL = "powershell",
  PUG = "pug",
  PYTHON = "python",
  R = "r",
  RAZOR = "razor",
  REDIS = "redis",
  REDSHIFT = "redshift",
  RUBY = "ruby",
  RUST = "rust",
  SB = "sb",
  SCHEME = "scheme",
  SCSS = "scss",
  SHELL = "shell",
  SOL = "sol",
  SQL = "sql",
  ST = "st",
  SWIFT = "swift",
  TCL = "tcl",
  TYPESCRIPT = "typescript",
  VB = "vb",
  XML = "xml",
  YAML = "yaml",
}

export const LANGUAGE_ICON: Record<string, JSX.Element> = {
  [Language.APEX]: DEFAULT(),
  [Language.AZCLI]: DEFAULT(),
  [Language.BAT]: DEFAULT(),
  [Language.C]: C(),
  [Language.CLOJURE]: DEFAULT(),
  [Language.COFFEESCRIPT]: DEFAULT(),
  [Language.CPP]: CPP(),
  [Language.CSHARP]: CSHARP(),
  [Language.CSP]: DEFAULT(),
  [Language.CSS]: CSS(),
  [Language.DOCKERFILE]: DOCKERFILE(),
  [Language.FSHARP]: DEFAULT(),
  [Language.GO]: GO(),
  [Language.GRAPHQL]: GRAPHQL(),
  [Language.HANDLEBARS]: DEFAULT(),
  [Language.HTML]: HTML(),
  [Language.INI]: DEFAULT(),
  [Language.JAVA]: JAVA(),
  [Language.JAVASCRIPT]: JAVASCRIPT(),
  [Language.JSON]: JSON(),
  [Language.KOTLIN]: KOTLIN(),
  [Language.LESS]: DEFAULT(),
  [Language.LUA]: LUA(),
  [Language.MARKDOWN]: MARKDOWN(),
  [Language.MSDAX]: DEFAULT(),
  [Language.MYSQL]: MYSQL(),
  [Language.OBJECTIVE_C]: DEFAULT(),
  [Language.PASCAL]: DEFAULT(),
  [Language.PERL]: DEFAULT(),
  [Language.PGSQL]: DEFAULT(),
  [Language.PHP]: DEFAULT(),
  [Language.PLAINTEXT]: DEFAULT(),
  [Language.POSTIATS]: DEFAULT(),
  [Language.POWERQUERY]: DEFAULT(),
  [Language.POWERSHELL]: DEFAULT(),
  [Language.PUG]: DEFAULT(),
  [Language.PYTHON]: DEFAULT(),
  [Language.R]: DEFAULT(),
  [Language.RAZOR]: DEFAULT(),
  [Language.REDIS]: DEFAULT(),
  [Language.REDSHIFT]: DEFAULT(),
  [Language.RUBY]: DEFAULT(),
  [Language.RUST]: DEFAULT(),
  [Language.SB]: DEFAULT(),
  [Language.SCHEME]: DEFAULT(),
  [Language.SCSS]: DEFAULT(),
  [Language.SHELL]: DEFAULT(),
  [Language.SOL]: DEFAULT(),
  [Language.SQL]: DEFAULT(),
  [Language.ST]: DEFAULT(),
  [Language.SWIFT]: DEFAULT(),
  [Language.TCL]: DEFAULT(),
  [Language.TYPESCRIPT]: TYPESCRIPT(),
  [Language.VB]: DEFAULT(),
  [Language.XML]: DEFAULT(),
  [Language.YAML]: DEFAULT(),
};
